---
title: "website test"
knit: (function(input_file, encoding) {
  out_dir <- 'docs';
  rmarkdown::render(input_file,
 encoding=encoding,
 output_file=file.path(dirname(input_file), out_dir, 'index.html'))})
author: "Jessica Klos"
date: "26 März 2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(leaflet)
```

## My map

```{r my_map, echo=FALSE}
boulderIcon <- icons(
  iconUrl = "http://www.bergfreunde.de/out/pictures/wysiwigpro/kalkulatoren/boulderer.svg",
  iconWidth = 38, iconHeight = 95,
  iconAnchorX = 22, iconAnchorY = 94,
)

bouldering_spots <- data.frame(lat = c(49.442747,49.479777,49.434361),
                               lng = c(10.959739,11.122492,11.097657))

bouldering_sites <- c(
  "<a href='https://www.boulderhalle-steinbock.de'>der steinbock</a>",
  "<a href='https://cafekraft.de/nuernberg'>Café Kraft</a>",
  "<a href='https://www.boulderhalle-e4.de/'>E4</a>"
)

bouldering_spots %>% 
  leaflet() %>%
  addTiles() %>%
  addMarkers(icon = boulderIcon, popup = bouldering_sites)
```
